apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: node-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30004
  type: NodePort
