apiVersion: apps/v1
kind: Deployment
metadata:
  name: pg-deployment
  labels:
    deployment: pg-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pg
  template:
    metadata:
      labels:
        app: pg
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          env:
            - name: POSTGRES_DB
              value: mydb
            - name: POSTGRES_USER
              value: root
            - name: POSTGRES_PASSWORD
              value: admin
          ports:
            - containerPort: 5432
          imagePullPolicy: Always
          volumeMounts:
            - name: pg-pv
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: pg-pv
          persistentVolumeClaim:
            claimName: pg-pvc
