apiVersion: v1
kind: PersistentVolume
metadata:
  name: pg-pv
spec:
  storageClassName: manual
  capacity:
    storage: 256Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /home/ubuntu/simpleurlshortener/pgdata
